{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Redwood Shipment Confirmation API",
    "description" : "API to confirm shipment details with Redwood, including status, references, shipping details, and billing.",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/MRINALNHCELAB/test/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "paths" : {
    "/shipment/confirmation" : {
      "post" : {
        "summary" : "Confirm Shipment Details",
        "description" : "Endpoint to confirm shipment details with Redwood, including pick slip status, shipping, billing, and item information.",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/ShipmentConfirmationRequestWrapper"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Student successfully created."
          },
          "400" : {
            "description" : "Bad request. Invalid input data."
          },
          "404" : {
            "description" : "Requested resource not found."
          },
          "500" : {
            "description" : "Internal server error occurred during shipment confirmation."
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "ShipmentConfirmationRequestWrapper" : {
        "type" : "object",
        "properties" : {
          "shipmentConfirmationRequest" : {
            "$ref" : "#/components/schemas/ShipmentConfirmationRequest"
          }
        }
      },
      "ShipmentConfirmationRequest" : {
        "type" : "object",
        "properties" : {
          "action" : {
            "type" : "string",
            "example" : "add"
          },
          "status" : {
            "$ref" : "#/components/schemas/Status"
          },
          "references" : {
            "$ref" : "#/components/schemas/References"
          },
          "shipping" : {
            "$ref" : "#/components/schemas/Shipping"
          },
          "invoice" : {
            "$ref" : "#/components/schemas/InvoiceReference"
          },
          "stops" : {
            "$ref" : "#/components/schemas/Stops"
          },
          "billing" : {
            "$ref" : "#/components/schemas/Billing"
          },
          "items" : {
            "$ref" : "#/components/schemas/ItemReference"
          }
        }
      },
      "Status" : {
        "type" : "object",
        "properties" : {
          "pickSlipStatus" : {
            "type" : "string",
            "example" : "CONFIRMED"
          }
        }
      },
      "References" : {
        "type" : "object",
        "properties" : {
          "primaryReference" : {
            "$ref" : "#/components/schemas/PrimaryReference"
          },
          "reference" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ReferenceItem"
            }
          }
        }
      },
      "PrimaryReference" : {
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string",
            "example" : "string"
          },
          "value" : {
            "type" : "string",
            "example" : "string"
          }
        }
      },
      "ReferenceItem" : {
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string",
            "description" : "Type of the reference item.",
            "example" : "string"
          },
          "value" : {
            "type" : "string",
            "description" : "Value of the reference item.",
            "example" : "string"
          }
        }
      },
      "Shipping" : {
        "type" : "object",
        "properties" : {
          "carrier" : {
            "type" : "string",
            "example" : "string"
          },
          "expectedDelivery" : {
            "type" : "string",
            "example" : "2025-01-15T05:58:08.977Z"
          },
          "carrierTracking" : {
            "type" : "string",
            "example" : "string"
          },
          "trackingType" : {
            "type" : "string",
            "example" : "null"
          }
        }
      },
      "InvoiceReference" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/Invoice"
        }
      },
      "Invoice" : {
        "type" : "object",
        "properties" : {
          "charges" : {
            "type" : "number",
            "example" : 0
          },
          "currency" : {
            "type" : "string",
            "example" : "string"
          },
          "chargeType" : {
            "type" : "string",
            "example" : "REDWOOD"
          }
        }
      },
      "Stops" : {
        "type" : "object",
        "properties" : {
          "pickup" : {
            "$ref" : "#/components/schemas/StopDetails"
          },
          "drop" : {
            "$ref" : "#/components/schemas/StopDetails"
          }
        }
      },
      "StopDetails" : {
        "type" : "object",
        "properties" : {
          "locationType" : {
            "type" : "string",
            "example" : "string"
          },
          "name" : {
            "type" : "string",
            "example" : "string"
          },
          "address1" : {
            "type" : "string",
            "example" : "string"
          },
          "address2" : {
            "type" : "string",
            "example" : "string"
          },
          "city" : {
            "type" : "string",
            "example" : "string"
          },
          "state" : {
            "type" : "string",
            "example" : "string"
          },
          "postalCode" : {
            "type" : "string",
            "example" : "string"
          },
          "country" : {
            "type" : "string",
            "example" : "string"
          },
          "contactInformation" : {
            "$ref" : "#/components/schemas/ContactInformationDetails"
          },
          "comments" : {
            "type" : "string",
            "example" : "string"
          }
        }
      },
      "ContactInformationDetails" : {
        "type" : "object",
        "properties" : {
          "phone" : {
            "type" : "string",
            "example" : "string"
          },
          "email" : {
            "type" : "string",
            "example" : "user@example.com"
          }
        }
      },
      "Billing" : {
        "type" : "object",
        "properties" : {
          "billToAddress" : {
            "$ref" : "#/components/schemas/BillToAddressInformation"
          }
        }
      },
      "BillToAddressInformation" : {
        "type" : "object",
        "properties" : {
          "locationCode" : {
            "type" : "string",
            "example" : "string"
          },
          "name" : {
            "type" : "string",
            "example" : "string"
          }
        }
      },
      "ItemReference" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/Item"
        }
      },
      "Item" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "example" : "string"
          },
          "description" : {
            "type" : "string",
            "example" : "string"
          },
          "orderQuantity" : {
            "$ref" : "#/components/schemas/Quantity"
          },
          "shippedQuantity" : {
            "$ref" : "#/components/schemas/Quantity"
          }
        }
      },
      "Quantity" : {
        "type" : "object",
        "properties" : {
          "uom" : {
            "type" : "string",
            "example" : "string"
          },
          "value" : {
            "type" : "integer",
            "example" : 0
          }
        }
      }
    }
  }
}